### ISSUE TITLE
NaN cuando se divide 0/0

### ISSUE THREAD

**Issue by nicolasvaldelamar** [Ali-Umed/Calculator#1]
Al dividir 0/0 sucede esto:
![IMG_1131](https://github.com/Ali-Umed/Calculator/assets/100731654/72f6a7f5-e516-498d-92a3-bcde494198d7)

**Comment by Ali-Umed** [comment]
Hi nicolasvaldelamar,

Thank you for reporting this issue! I've reviewed your report and made the necessary changes to fix it. The issue should now be resolved in the latest version of the project. Now insteand of the Nan now it is undifind when 0/0

If you have any further questions or encounter any other issues, please don't hesitate to let me know.

Best regards,
Ali Umed
